name: ci-sollievo-workflow
on:
  push:
    branches:
      - main
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.23'
    
    - name: build and zip with makefile
      run: make zip
    
    - name: create github release
      uses: "softprops/action-gh-release@v2"
      with:
        files: build/*.zip
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        make_latest: true
      env:
        GOROOT: /opt/hostedtoolcache/go/1.23.2/x64
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    